services:
  server:
    build:
      context: ./nginx/
      args:
        - SERVER_UID
        - SERVER_GID
    volumes:
      - /tmp:/tmp
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "${NGINX_EXTERNAL_PORT}:${NGINX_SSL_PORT}"
    environment:
      - API_ENDPOINTS
      - FRONTEND_ENDPOINTS
      - ALLOWED_CLIENT_IP
      - NGINX_SSL_PORT
      - UWSGI_SOCKET
      - CERT_DIR
      - SSL_CERT
      - SSL_CERT_KEY
      - SSL_CLIENT_CERT
  mc_server:
    build: 
      dockerfile: ./microcontroller/Dockerfile
      context: .
    devices: 
      - "${SERIAL_DEVICE}:${SERIAL_DEVICE}"
    ports:
      - "${MC_SERVER_PORT}"
    environment:
      - SERIAL_ENABLED
      - SERIAL_BAUD
      - SERIAL_DEVICE
      - MC_SERVER_PORT
  app:
    build:
      context: .
      args:
        - SERVER_UID
        - VIDEO_GID
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
    volumes:
      - /tmp:/tmp # Shared socket directory
      - /opt/vc:/opt/vc # Video libraries
      - ./instance:/watchtower/instance # Recordings & runtime configs
      - /var/log/watchtower:/var/log/watchtower # Logs
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - WATCHTOWER_CONFIG
      - LOG_CONFIG
      - UWSGI_SOCKET
      - MC_SERVER_HOST=mc_server
      - MC_SERVER_PORT
      - SERIAL_ENABLED
