services:
  server:
    build:
      context: ./nginx/
      args: # Used in the nginx Dockerfile
        - SERVER_UID
        - SERVER_GID
    user: "${SERVER_UID}:${SERVER_GID}"
    volumes:
      - /tmp:/tmp
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "${NGINX_EXTERNAL_PORT}:${NGINX_SSL_PORT}"
    environment:
      - API_ENDPOINTS
      - FRONTEND_ENDPOINTS
      - NGINX_SSL_PORT
      - UWSGI_SOCKET
      - CERT_DIR
      - SSL_CERT
      - SSL_CERT_KEY
      - SSL_CLIENT_CERT
  app:
    build:
      context: .
      args: # Used in the Watchtower Dockerfile
        - SERVER_UID
        - SERVER_GID
    volumes:
      - /tmp:/tmp
      - ./instance:/watchtower/instance/
      - /var/log/watchtower:/var/log/watchtower
    environment:
      - UWSGI_SOCKET
  